### ISSUE TITLE
add fly limit

### ISSUE THREAD

**Issue by Driesboy** [MCrafterss/MFlyCommand#2]

**Comment by AmiroEmad** [comment]
it will make the plugin very laggy + the plugin name is mflycommand not mfly limit

**Comment by Driesboy** [comment]
can you make a option to add that

**Comment by Dog2puppy** [comment]
I could implement that at some point I think.

**Comment by iPocket** [comment]
@Dog2puppy I can too, but it's not the topic of the plugin.
